# Generated by Django 4.2.7 on 2023-12-03 12:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a pet category (e.g. Dogs, Cats, Birds etc.)', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the pet', max_length=1000)),
                ('microchip_id', models.CharField(help_text='13 Character Microchip ID', max_length=13, unique=True, verbose_name='Microchip ID')),
                ('breed', models.CharField(max_length=200)),
                ('category', models.ManyToManyField(help_text='Select a category for this pet', to='PetsFinderApp.category')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='PetsFinderApp.owner')),
            ],
        ),
        migrations.CreateModel(
            name='PetInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular pet instance', primary_key=True, serialize=False)),
                ('breed', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Available'), ('p', 'Pending Adoption'), ('r', 'Reserved')], default='a', help_text='Pet availability', max_length=1)),
                ('pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PetsFinderApp.pet')),
            ],
            options={
                'ordering': ['birth_date'],
            },
        ),
    ]
