# Generated by Django 4.2.7 on 2023-11-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='text',
        ),
        migrations.AddField(
            model_name='pet',
            name='Place',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.TextField(default=''),
        ),
    ]
