# Generated by Django 4.2.7 on 2023-11-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_remove_pet_text_pet_place_pet_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='Place',
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.TextField(default='', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='pet',
            name='place',
            field=models.TextField(default='', verbose_name='Place'),
        ),
    ]
